import json
import re

# 你自己的 JSON 数据（完整粘贴）
json_str = '''
{
    "success": true,
    "code": 200,
    "message": null,
    "errorCode": null,
    "data": [
        {
            "componentId": 12256,
            "componentCode": "C11702",
            "componentName": null,
            "componentType": null,
            "orderLibraryType": null,
            "componentModel": null,
            "componentSpecification": null,
            "componentBrand": null,
            "encapsulationNumber": null,
            "mergedComponentCode": null,
            "hotLevel": null,
            "presaleOrderFlag": null,
            "mailComponentFlag": false,
            "paramTextAll": null,
            "assemblyMode": "smtWeld",
            "assemblyModeBatch": "smtWeld",
            "componentNameHigh": null,
            "componentCodeHigh": null,
            "componentBrandHigh": null,
            "componentSpecificationHigh": null,
            "componentModelHigh": null,
            "componentTypeHigh": null,
            "maxDiscountAmount": 3.80000,
            "maxOfferPercent": 7.9200,
            "consultPrice": 0.00480,
            "wholePrice": 0.00442,
            "priceList": [
                {
                    "componentId": 12256,
                    "componentCode": "C11702",
                    "startNumber": 1,
                    "endNumber": 999,
                    "productPrice": 0.00670,
                    "wholePrice": 0.00442,
                    "encapsulationNumber": null
                },
                {
                    "componentId": 12256,
                    "componentCode": "C11702",
                    "startNumber": 1000,
                    "endNumber": 2999,
                    "productPrice": 0.00570,
                    "wholePrice": 0.00442,
                    "encapsulationNumber": null
                },
                {
                    "componentId": 12256,
                    "componentCode": "C11702",
                    "startNumber": 3000,
                    "endNumber": 9999,
                    "productPrice": 0.00510,
                    "wholePrice": 0.00442,
                    "encapsulationNumber": null
                },
                {
                    "componentId": 12256,
                    "componentCode": "C11702",
                    "startNumber": 10000,
                    "endNumber": 49999,
                    "productPrice": 0.00480,
                    "wholePrice": 0.00442,
                    "encapsulationNumber": null
                },
                {
                    "componentId": 12256,
                    "componentCode": "C11702",
                    "startNumber": 50000,
                    "endNumber": -1,
                    "productPrice": 0.00440,
                    "wholePrice": 0.00442,
                    "encapsulationNumber": null
                }
            ],
            "componentProductType": null,
            "stockNum": 4273743,
            "canPreSaleStockNum": 1264397,
            "paramAllTextFront": null,
            "showPlateChangeMaterialCouponFlag": null,
            "plateCouponMoney": null,
            "materialGrade": null,
            "collectionsFlag": false,
            "status": null,
            "existReplaceFlag": false,
            "preferredComponentFlag": null,
            "eccnCode": "",
            "startsPriceAt": 0.00440,
            "prePutFlag": false,
            "esScore": null,
            "topComponentFlag": false,
            "servicePubData": null,
            "assemblyComponentFlag": false,
            "priceInquiryFlag": false
        },
        {
            "componentId": 17853,
            "componentCode": "C17168",
            "componentName": null,
            "componentType": null,
            "orderLibraryType": null,
            "componentModel": null,
            "componentSpecification": null,
            "componentBrand": null,
            "encapsulationNumber": null,
            "mergedComponentCode": null,
            "hotLevel": null,
            "presaleOrderFlag": null,
            "mailComponentFlag": false,
            "paramTextAll": null,
            "assemblyMode": "smtWeld",
            "assemblyModeBatch": "smtWeld",
            "componentNameHigh": null,
            "componentCodeHigh": null,
            "componentBrandHigh": null,
            "componentSpecificationHigh": null,
            "componentModelHigh": null,
            "componentTypeHigh": null,
            "maxDiscountAmount": 3.70000,
            "maxOfferPercent": 8.0400,
            "consultPrice": 0.00460,
            "wholePrice": 0.00423,
            "priceList": [
                {
                    "componentId": 17853,
                    "componentCode": "C17168",
                    "startNumber": 1,
                    "endNumber": 999,
                    "productPrice": 0.00660,
                    "wholePrice": 0.00423,
                    "encapsulationNumber": null
                },
                {
                    "componentId": 17853,
                    "componentCode": "C17168",
                    "startNumber": 1000,
                    "endNumber": 2999,
                    "productPrice": 0.00550,
                    "wholePrice": 0.00423,
                    "encapsulationNumber": null
                },
                {
                    "componentId": 17853,
                    "componentCode": "C17168",
                    "startNumber": 3000,
                    "endNumber": 9999,
                    "productPrice": 0.00490,
                    "wholePrice": 0.00423,
                    "encapsulationNumber": null
                },
                {
                    "componentId": 17853,
                    "componentCode": "C17168",
                    "startNumber": 10000,
                    "endNumber": 49999,
                    "productPrice": 0.00460,
                    "wholePrice": 0.00423,
                    "encapsulationNumber": null
                },
                {
                    "componentId": 17853,
                    "componentCode": "C17168",
                    "startNumber": 50000,
                    "endNumber": -1,
                    "productPrice": 0.00410,
                    "wholePrice": 0.00423,
                    "encapsulationNumber": null
                }
            ],
            "componentProductType": null,
            "stockNum": 5154930,
            "canPreSaleStockNum": 3258515,
            "paramAllTextFront": null,
            "showPlateChangeMaterialCouponFlag": null,
            "plateCouponMoney": null,
            "materialGrade": null,
            "collectionsFlag": false,
            "status": null,
            "existReplaceFlag": false,
            "preferredComponentFlag": null,
            "eccnCode": "",
            "startsPriceAt": 0.00410,
            "prePutFlag": false,
            "esScore": null,
            "topComponentFlag": false,
            "servicePubData": null,
            "assemblyComponentFlag": false,
            "priceInquiryFlag": false
        },
        {
            "componentId": 25819,
            "componentCode": "C25076",
            "componentName": null,
            "componentType": null,
            "orderLibraryType": null,
            "componentModel": null,
            "componentSpecification": null,
            "componentBrand": null,
            "encapsulationNumber": null,
            "mergedComponentCode": null,
            "hotLevel": null,
            "presaleOrderFlag": null,
            "mailComponentFlag": false,
            "paramTextAll": null,
            "assemblyMode": "smtWeld",
            "assemblyModeBatch": "smtWeld",
            "componentNameHigh": null,
            "componentCodeHigh": null,
            "componentBrandHigh": null,
            "componentSpecificationHigh": null,
            "componentModelHigh": null,
            "componentTypeHigh": null,
            "maxDiscountAmount": 4.20000,
            "maxOfferPercent": 7.9200,
            "consultPrice": 0.00530,
            "wholePrice": 0.00488,
            "priceList": [
                {
                    "componentId": 25819,
                    "componentCode": "C25076",
                    "startNumber": 1,
                    "endNumber": 999,
                    "productPrice": 0.00720,
                    "wholePrice": 0.00488,
                    "encapsulationNumber": null
                },
                {
                    "componentId": 25819,
                    "componentCode": "C25076",
                    "startNumber": 1000,
                    "endNumber": 2999,
                    "productPrice": 0.00610,
                    "wholePrice": 0.00488,
                    "encapsulationNumber": null
                },
                {
                    "componentId": 25819,
                    "componentCode": "C25076",
                    "startNumber": 3000,
                    "endNumber": 9999,
                    "productPrice": 0.00550,
                    "wholePrice": 0.00488,
                    "encapsulationNumber": null
                },
                {
                    "componentId": 25819,
                    "componentCode": "C25076",
                    "startNumber": 10000,
                    "endNumber": 49999,
                    "productPrice": 0.00530,
                    "wholePrice": 0.00488,
                    "encapsulationNumber": null
                },
                {
                    "componentId": 25819,
                    "componentCode": "C25076",
                    "startNumber": 50000,
                    "endNumber": -1,
                    "productPrice": 0.00480,
                    "wholePrice": 0.00488,
                    "encapsulationNumber": null
                }
            ],
            "componentProductType": null,
            "stockNum": 3909026,
            "canPreSaleStockNum": 2659348,
            "paramAllTextFront": null,
            "showPlateChangeMaterialCouponFlag": null,
            "plateCouponMoney": null,
            "materialGrade": null,
            "collectionsFlag": false,
            "status": null,
            "existReplaceFlag": false,
            "preferredComponentFlag": null,
            "eccnCode": "",
            "startsPriceAt": 0.00480,
            "prePutFlag": false,
            "esScore": null,
            "topComponentFlag": false,
            "servicePubData": null,
            "assemblyComponentFlag": false,
            "priceInquiryFlag": false
        },
        {
            "componentId": 25820,
            "componentCode": "C25077",
            "componentName": null,
            "componentType": null,
            "orderLibraryType": null,
            "componentModel": null,
            "componentSpecification": null,
            "componentBrand": null,
            "encapsulationNumber": null,
            "mergedComponentCode": null,
            "hotLevel": null,
            "presaleOrderFlag": null,
            "mailComponentFlag": false,
            "paramTextAll": null,
            "assemblyMode": "smtWeld",
            "assemblyModeBatch": "smtWeld",
            "componentNameHigh": null,
            "componentCodeHigh": null,
            "componentBrandHigh": null,
            "componentSpecificationHigh": null,
            "componentModelHigh": null,
            "componentTypeHigh": null,
            "maxDiscountAmount": 2.60000,
            "maxOfferPercent": 8.1300,
            "consultPrice": 0.00320,
            "wholePrice": 0.00294,
            "priceList": [
                {
                    "componentId": 25820,
                    "componentCode": "C25077",
                    "startNumber": 1,
                    "endNumber": 999,
                    "productPrice": 0.00520,
                    "wholePrice": 0.00294,
                    "encapsulationNumber": null
                },
                {
                    "componentId": 25820,
                    "componentCode": "C25077",
                    "startNumber": 1000,
                    "endNumber": 2999,
                    "productPrice": 0.00410,
                    "wholePrice": 0.00294,
                    "encapsulationNumber": null
                },
                {
                    "componentId": 25820,
                    "componentCode": "C25077",
                    "startNumber": 3000,
                    "endNumber": 9999,
                    "productPrice": 0.00350,
                    "wholePrice": 0.00294,
                    "encapsulationNumber": null
                },
                {
                    "componentId": 25820,
                    "componentCode": "C25077",
                    "startNumber": 10000,
                    "endNumber": 49999,
                    "productPrice": 0.00320,
                    "wholePrice": 0.00294,
                    "encapsulationNumber": null
                },
                {
                    "componentId": 25820,
                    "componentCode": "C25077",
                    "startNumber": 50000,
                    "endNumber": -1,
                    "productPrice": 0.00280,
                    "wholePrice": 0.00294,
                    "encapsulationNumber": null
                }
            ],
            "componentProductType": null,
            "stockNum": 2014494,
            "canPreSaleStockNum": 1407855,
            "paramAllTextFront": null,
            "showPlateChangeMaterialCouponFlag": null,
            "plateCouponMoney": null,
            "materialGrade": null,
            "collectionsFlag": false,
            "status": null,
            "existReplaceFlag": false,
            "preferredComponentFlag": null,
            "eccnCode": "",
            "startsPriceAt": 0.00280,
            "prePutFlag": false,
            "esScore": null,
            "topComponentFlag": false,
            "servicePubData": null,
            "assemblyComponentFlag": false,
            "priceInquiryFlag": false
        },
        {
            "componentId": 25822,
            "componentCode": "C25079",
            "componentName": null,
            "componentType": null,
            "orderLibraryType": null,
            "componentModel": null,
            "componentSpecification": null,
            "componentBrand": null,
            "encapsulationNumber": null,
            "mergedComponentCode": null,
            "hotLevel": null,
            "presaleOrderFlag": null,
            "mailComponentFlag": false,
            "paramTextAll": null,
            "assemblyMode": "smtWeld",
            "assemblyModeBatch": "smtWeld",
            "componentNameHigh": null,
            "componentCodeHigh": null,
            "componentBrandHigh": null,
            "componentSpecificationHigh": null,
            "componentModelHigh": null,
            "componentTypeHigh": null,
            "maxDiscountAmount": 5.30000,
            "maxOfferPercent": 8.0300,
            "consultPrice": 0.00660,
            "wholePrice": 0.00607,
            "priceList": [
                {
                    "componentId": 25822,
                    "componentCode": "C25079",
                    "startNumber": 1,
                    "endNumber": 999,
                    "productPrice": 0.00840,
                    "wholePrice": 0.00607,
                    "encapsulationNumber": null
                },
                {
                    "componentId": 25822,
                    "componentCode": "C25079",
                    "startNumber": 1000,
                    "endNumber": 2999,
                    "productPrice": 0.00740,
                    "wholePrice": 0.00607,
                    "encapsulationNumber": null
                },
                {
                    "componentId": 25822,
                    "componentCode": "C25079",
                    "startNumber": 3000,
                    "endNumber": 9999,
                    "productPrice": 0.00680,
                    "wholePrice": 0.00607,
                    "encapsulationNumber": null
                },
                {
                    "componentId": 25822,
                    "componentCode": "C25079",
                    "startNumber": 10000,
                    "endNumber": 49999,
                    "productPrice": 0.00660,
                    "wholePrice": 0.00607,
                    "encapsulationNumber": null
                },
                {
                    "componentId": 25822,
                    "componentCode": "C25079",
                    "startNumber": 50000,
                    "endNumber": -1,
                    "productPrice": 0.00620,
                    "wholePrice": 0.00607,
                    "encapsulationNumber": null
                }
            ],
            "componentProductType": null,
            "stockNum": 432014,
            "canPreSaleStockNum": 303052,
            "paramAllTextFront": null,
            "showPlateChangeMaterialCouponFlag": null,
            "plateCouponMoney": null,
            "materialGrade": null,
            "collectionsFlag": false,
            "status": null,
            "existReplaceFlag": false,
            "preferredComponentFlag": null,
            "eccnCode": "",
            "startsPriceAt": 0.00607,
            "prePutFlag": false,
            "esScore": null,
            "topComponentFlag": false,
            "servicePubData": null,
            "assemblyComponentFlag": false,
            "priceInquiryFlag": false
        },
        {
            "componentId": 25830,
            "componentCode": "C25087",
            "componentName": null,
            "componentType": null,
            "orderLibraryType": null,
            "componentModel": null,
            "componentSpecification": null,
            "componentBrand": null,
            "encapsulationNumber": null,
            "mergedComponentCode": null,
            "hotLevel": null,
            "presaleOrderFlag": null,
            "mailComponentFlag": false,
            "paramTextAll": null,
            "assemblyMode": "smtWeld",
            "assemblyModeBatch": "smtWeld",
            "componentNameHigh": null,
            "componentCodeHigh": null,
            "componentBrandHigh": null,
            "componentSpecificationHigh": null,
            "componentModelHigh": null,
            "componentTypeHigh": null,
            "maxDiscountAmount": 3.40000,
            "maxOfferPercent": 7.9100,
            "consultPrice": 0.00430,
            "wholePrice": 0.00396,
            "priceList": [
                {
                    "componentId": 25830,
                    "componentCode": "C25087",
                    "startNumber": 1,
                    "endNumber": 999,
                    "productPrice": 0.00620,
                    "wholePrice": 0.00396,
                    "encapsulationNumber": null
                },
                {
                    "componentId": 25830,
                    "componentCode": "C25087",
                    "startNumber": 1000,
                    "endNumber": 2999,
                    "productPrice": 0.00510,
                    "wholePrice": 0.00396,
                    "encapsulationNumber": null
                },
                {
                    "componentId": 25830,
                    "componentCode": "C25087",
                    "startNumber": 3000,
                    "endNumber": 9999,
                    "productPrice": 0.00460,
                    "wholePrice": 0.00396,
                    "encapsulationNumber": null
                },
                {
                    "componentId": 25830,
                    "componentCode": "C25087",
                    "startNumber": 10000,
                    "endNumber": 49999,
                    "productPrice": 0.00430,
                    "wholePrice": 0.00396,
                    "encapsulationNumber": null
                },
                {
                    "componentId": 25830,
                    "componentCode": "C25087",
                    "startNumber": 50000,
                    "endNumber": -1,
                    "productPrice": 0.00400,
                    "wholePrice": 0.00396,
                    "encapsulationNumber": null
                }
            ],
            "componentProductType": null,
            "stockNum": 591139,
            "canPreSaleStockNum": 360438,
            "paramAllTextFront": null,
            "showPlateChangeMaterialCouponFlag": null,
            "plateCouponMoney": null,
            "materialGrade": null,
            "collectionsFlag": false,
            "status": null,
            "existReplaceFlag": false,
            "preferredComponentFlag": null,
            "eccnCode": "",
            "startsPriceAt": 0.00396,
            "prePutFlag": false,
            "esScore": null,
            "topComponentFlag": false,
            "servicePubData": null,
            "assemblyComponentFlag": false,
            "priceInquiryFlag": false
        },
        {
            "componentId": 25834,
            "componentCode": "C25091",
            "componentName": null,
            "componentType": null,
            "orderLibraryType": null,
            "componentModel": null,
            "componentSpecification": null,
            "componentBrand": null,
            "encapsulationNumber": null,
            "mergedComponentCode": null,
            "hotLevel": null,
            "presaleOrderFlag": null,
            "mailComponentFlag": false,
            "paramTextAll": null,
            "assemblyMode": "smtWeld",
            "assemblyModeBatch": "smtWeld",
            "componentNameHigh": null,
            "componentCodeHigh": null,
            "componentBrandHigh": null,
            "componentSpecificationHigh": null,
            "componentModelHigh": null,
            "componentTypeHigh": null,
            "maxDiscountAmount": 3.20000,
            "maxOfferPercent": 7.8800,
            "consultPrice": 0.00406,
            "wholePrice": 0.00374,
            "priceList": [
                {
                    "componentId": 25834,
                    "componentCode": "C25091",
                    "startNumber": 1,
                    "endNumber": 999,
                    "productPrice": 0.00574,
                    "wholePrice": 0.00374,
                    "encapsulationNumber": null
                },
                {
                    "componentId": 25834,
                    "componentCode": "C25091",
                    "startNumber": 1000,
                    "endNumber": 2999,
                    "productPrice": 0.00475,
                    "wholePrice": 0.00374,
                    "encapsulationNumber": null
                },
                {
                    "componentId": 25834,
                    "componentCode": "C25091",
                    "startNumber": 3000,
                    "endNumber": 9999,
                    "productPrice": 0.00426,
                    "wholePrice": 0.00374,
                    "encapsulationNumber": null
                },
                {
                    "componentId": 25834,
                    "componentCode": "C25091",
                    "startNumber": 10000,
                    "endNumber": 49999,
                    "productPrice": 0.00406,
                    "wholePrice": 0.00374,
                    "encapsulationNumber": null
                },
                {
                    "componentId": 25834,
                    "componentCode": "C25091",
                    "startNumber": 50000,
                    "endNumber": -1,
                    "productPrice": 0.00366,
                    "wholePrice": 0.00374,
                    "encapsulationNumber": null
                }
            ],
            "componentProductType": null,
            "stockNum": 642518,
            "canPreSaleStockNum": 455159,
            "paramAllTextFront": null,
            "showPlateChangeMaterialCouponFlag": null,
            "plateCouponMoney": null,
            "materialGrade": null,
            "collectionsFlag": false,
            "status": null,
            "existReplaceFlag": false,
            "preferredComponentFlag": null,
            "eccnCode": "",
            "startsPriceAt": 0.00366,
            "prePutFlag": false,
            "esScore": null,
            "topComponentFlag": false,
            "servicePubData": null,
            "assemblyComponentFlag": false,
            "priceInquiryFlag": false
        },
        {
            "componentId": 25835,
            "componentCode": "C25092",
            "componentName": null,
            "componentType": null,
            "orderLibraryType": null,
            "componentModel": null,
            "componentSpecification": null,
            "componentBrand": null,
            "encapsulationNumber": null,
            "mergedComponentCode": null,
            "hotLevel": null,
            "presaleOrderFlag": null,
            "mailComponentFlag": false,
            "paramTextAll": null,
            "assemblyMode": "smtWeld",
            "assemblyModeBatch": "smtWeld",
            "componentNameHigh": null,
            "componentCodeHigh": null,
            "componentBrandHigh": null,
            "componentSpecificationHigh": null,
            "componentModelHigh": null,
            "componentTypeHigh": null,
            "maxDiscountAmount": 2.80000,
            "maxOfferPercent": 8.0000,
            "consultPrice": 0.00350,
            "wholePrice": 0.00322,
            "priceList": [
                {
                    "componentId": 25835,
                    "componentCode": "C25092",
                    "startNumber": 1,
                    "endNumber": 999,
                    "productPrice": 0.00540,
                    "wholePrice": 0.00322,
                    "encapsulationNumber": null
                },
                {
                    "componentId": 25835,
                    "componentCode": "C25092",
                    "startNumber": 1000,
                    "endNumber": 2999,
                    "productPrice": 0.00430,
                    "wholePrice": 0.00322,
                    "encapsulationNumber": null
                },
                {
                    "componentId": 25835,
                    "componentCode": "C25092",
                    "startNumber": 3000,
                    "endNumber": 9999,
                    "productPrice": 0.00370,
                    "wholePrice": 0.00322,
                    "encapsulationNumber": null
                },
                {
                    "componentId": 25835,
                    "componentCode": "C25092",
                    "startNumber": 10000,
                    "endNumber": 49999,
                    "productPrice": 0.00350,
                    "wholePrice": 0.00322,
                    "encapsulationNumber": null
                },
                {
                    "componentId": 25835,
                    "componentCode": "C25092",
                    "startNumber": 50000,
                    "endNumber": -1,
                    "productPrice": 0.00290,
                    "wholePrice": 0.00322,
                    "encapsulationNumber": null
                }
            ],
            "componentProductType": null,
            "stockNum": 1323995,
            "canPreSaleStockNum": 316900,
            "paramAllTextFront": null,
            "showPlateChangeMaterialCouponFlag": null,
            "plateCouponMoney": null,
            "materialGrade": null,
            "collectionsFlag": false,
            "status": null,
            "existReplaceFlag": false,
            "preferredComponentFlag": null,
            "eccnCode": "",
            "startsPriceAt": 0.00290,
            "prePutFlag": false,
            "esScore": null,
            "topComponentFlag": false,
            "servicePubData": null,
            "assemblyComponentFlag": false,
            "priceInquiryFlag": false
        },
        {
            "componentId": 25847,
            "componentCode": "C25104",
            "componentName": null,
            "componentType": null,
            "orderLibraryType": null,
            "componentModel": null,
            "componentSpecification": null,
            "componentBrand": null,
            "encapsulationNumber": null,
            "mergedComponentCode": null,
            "hotLevel": null,
            "presaleOrderFlag": null,
            "mailComponentFlag": false,
            "paramTextAll": null,
            "assemblyMode": "smtWeld",
            "assemblyModeBatch": "smtWeld",
            "componentNameHigh": null,
            "componentCodeHigh": null,
            "componentBrandHigh": null,
            "componentSpecificationHigh": null,
            "componentModelHigh": null,
            "componentTypeHigh": null,
            "maxDiscountAmount": 4.00000,
            "maxOfferPercent": 8.0800,
            "consultPrice": 0.00495,
            "wholePrice": 0.00455,
            "priceList": [
                {
                    "componentId": 25847,
                    "componentCode": "C25104",
                    "startNumber": 1,
                    "endNumber": 999,
                    "productPrice": 0.00683,
                    "wholePrice": 0.00455,
                    "encapsulationNumber": null
                },
                {
                    "componentId": 25847,
                    "componentCode": "C25104",
                    "startNumber": 1000,
                    "endNumber": 2999,
                    "productPrice": 0.00574,
                    "wholePrice": 0.00455,
                    "encapsulationNumber": null
                },
                {
                    "componentId": 25847,
                    "componentCode": "C25104",
                    "startNumber": 3000,
                    "endNumber": 9999,
                    "productPrice": 0.00525,
                    "wholePrice": 0.00455,
                    "encapsulationNumber": null
                },
                {
                    "componentId": 25847,
                    "componentCode": "C25104",
                    "startNumber": 10000,
                    "endNumber": 49999,
                    "productPrice": 0.00495,
                    "wholePrice": 0.00455,
                    "encapsulationNumber": null
                },
                {
                    "componentId": 25847,
                    "componentCode": "C25104",
                    "startNumber": 50000,
                    "endNumber": -1,
                    "productPrice": 0.00396,
                    "wholePrice": 0.00455,
                    "encapsulationNumber": null
                }
            ],
            "componentProductType": null,
            "stockNum": 1119857,
            "canPreSaleStockNum": 874293,
            "paramAllTextFront": null,
            "showPlateChangeMaterialCouponFlag": null,
            "plateCouponMoney": null,
            "materialGrade": null,
            "collectionsFlag": false,
            "status": null,
            "existReplaceFlag": false,
            "preferredComponentFlag": null,
            "eccnCode": "",
            "startsPriceAt": 0.00396,
            "prePutFlag": false,
            "esScore": null,
            "topComponentFlag": false,
            "servicePubData": null,
            "assemblyComponentFlag": false,
            "priceInquiryFlag": false
        },
        {
            "componentId": 4516,
            "componentCode": "C4109",
            "componentName": null,
            "componentType": null,
            "orderLibraryType": null,
            "componentModel": null,
            "componentSpecification": null,
            "componentBrand": null,
            "encapsulationNumber": null,
            "mergedComponentCode": null,
            "hotLevel": null,
            "presaleOrderFlag": null,
            "mailComponentFlag": false,
            "paramTextAll": null,
            "assemblyMode": "smtWeld",
            "assemblyModeBatch": "smtWeld",
            "componentNameHigh": null,
            "componentCodeHigh": null,
            "componentBrandHigh": null,
            "componentSpecificationHigh": null,
            "componentModelHigh": null,
            "componentTypeHigh": null,
            "maxDiscountAmount": 2.20000,
            "maxOfferPercent": 7.8600,
            "consultPrice": 0.00280,
            "wholePrice": 0.00258,
            "priceList": [
                {
                    "componentId": 4516,
                    "componentCode": "C4109",
                    "startNumber": 1,
                    "endNumber": 999,
                    "productPrice": 0.00460,
                    "wholePrice": 0.00258,
                    "encapsulationNumber": null
                },
                {
                    "componentId": 4516,
                    "componentCode": "C4109",
                    "startNumber": 1000,
                    "endNumber": 2999,
                    "productPrice": 0.00360,
                    "wholePrice": 0.00258,
                    "encapsulationNumber": null
                },
                {
                    "componentId": 4516,
                    "componentCode": "C4109",
                    "startNumber": 3000,
                    "endNumber": 9999,
                    "productPrice": 0.00310,
                    "wholePrice": 0.00258,
                    "encapsulationNumber": null
                },
                {
                    "componentId": 4516,
                    "componentCode": "C4109",
                    "startNumber": 10000,
                    "endNumber": 49999,
                    "productPrice": 0.00280,
                    "wholePrice": 0.00258,
                    "encapsulationNumber": null
                },
                {
                    "componentId": 4516,
                    "componentCode": "C4109",
                    "startNumber": 50000,
                    "endNumber": -1,
                    "productPrice": 0.00250,
                    "wholePrice": 0.00258,
                    "encapsulationNumber": null
                }
            ],
            "componentProductType": null,
            "stockNum": 2042298,
            "canPreSaleStockNum": 1364393,
            "paramAllTextFront": null,
            "showPlateChangeMaterialCouponFlag": null,
            "plateCouponMoney": null,
            "materialGrade": null,
            "collectionsFlag": false,
            "status": null,
            "existReplaceFlag": false,
            "preferredComponentFlag": null,
            "eccnCode": "",
            "startsPriceAt": 0.00250,
            "prePutFlag": false,
            "esScore": null,
            "topComponentFlag": false,
            "servicePubData": null,
            "assemblyComponentFlag": false,
            "priceInquiryFlag": false
        }
    ]
}
'''

data = json.loads(json_str)
components = data['data']

# 存储电阻值（单位：欧姆）
ohm_values = []

for comp in components:
    code = comp.get('componentCode', '')
    # 提取数字部分（支持 C11702、R1002 等格式，取第一段连续数字）
    match = re.search(r'\d+', code)
    if match:
        ohm = int(match.group())
        ohm_values.append(ohm)

# 转换为带 K/M 的表达式
formatted_values = []
for ohm in ohm_values:
    if ohm >= 1_000_000:
        val = ohm / 1_000_000
        # 去掉多余的 .0 或 .000 后缀
        formatted_values.append(f"{val:.6f}".rstrip('0').rstrip('.') + '*M')
    else:
        val = ohm / 1000
        formatted_values.append(f"{val:.6f}".rstrip('0').rstrip('.') + '*K')

# 输出标准电阻表格式
print("K = 1000")
print("M = 1000000")
print("\nR_VALUES = (")
for i, v in enumerate(formatted_values):
    end = "," if i < len(formatted_values)-1 else ""
    print(f"    {v}{end}")
print(")")
